-- Placeholder generated from COMPLETE_STRUCTURE.txt
-- Path: bounded-contexts/tenancy-identity/identity-core/src/main/resources/db/migration/V004__create_external_identity_table.sql
-- TODO: Add SQL statements.
