-- Placeholder generated from COMPLETE_STRUCTURE.txt
-- Path: bounded-contexts/finance/finance-assets/assets-infrastructure/src/main/resources/db/migration/V2__create_fixed_asset_tables.sql
-- TODO: Add SQL statements.
