-- Placeholder generated from COMPLETE_STRUCTURE.txt
-- Path: bounded-contexts/finance/finance-assets/assets-infrastructure/src/main/resources/db/migration/V3__create_depreciation_tables.sql
-- TODO: Add SQL statements.
