-- Placeholder generated from COMPLETE_STRUCTURE.txt
-- Path: bounded-contexts/finance/finance-assets/assets-infrastructure/src/main/resources/db/migration/V4__create_disposal_tables.sql
-- TODO: Add SQL statements.
