-- Placeholder generated from COMPLETE_STRUCTURE.txt
-- Path: bounded-contexts/finance/finance-ar/ar-infrastructure/src/main/resources/db/migration/V1__create_ar_schema.sql
-- TODO: Add SQL statements.
