-- Placeholder generated from COMPLETE_STRUCTURE.txt
-- Path: bounded-contexts/finance/finance-ar/ar-infrastructure/src/main/resources/db/migration/V2__create_invoice_tables.sql
-- TODO: Add SQL statements.
