-- Placeholder generated from COMPLETE_STRUCTURE.txt
-- Path: bounded-contexts/finance/finance-ar/ar-infrastructure/src/main/resources/db/migration/V4__create_event_outbox_table.sql
-- TODO: Add SQL statements.
