-- Placeholder generated from COMPLETE_STRUCTURE.txt
-- Path: bounded-contexts/finance/finance-ar/ar-infrastructure/src/main/resources/db/migration/V5__create_event_inbox_table.sql
-- TODO: Add SQL statements.
