-- Placeholder generated from COMPLETE_STRUCTURE.txt
-- Path: bounded-contexts/finance/finance-ap/ap-infrastructure/src/main/resources/db/migration/V6__create_event_inbox_table.sql
-- TODO: Add SQL statements.
