-- Placeholder generated from COMPLETE_STRUCTURE.txt
-- Path: bounded-contexts/finance/finance-tax/tax-infrastructure/src/main/resources/db/migration/V2__create_tax_code_tables.sql
-- TODO: Add SQL statements.
