-- Placeholder generated from COMPLETE_STRUCTURE.txt
-- Path: bounded-contexts/finance/finance-tax/tax-infrastructure/src/main/resources/db/migration/V5__create_withholding_tables.sql
-- TODO: Add SQL statements.
