-- Placeholder generated from COMPLETE_STRUCTURE.txt
-- Path: bounded-contexts/finance/finance-tax/tax-infrastructure/src/main/resources/db/migration/V7__create_event_inbox_table.sql
-- TODO: Add SQL statements.
