-- Placeholder generated from COMPLETE_STRUCTURE.txt
-- Path: bounded-contexts/finance/finance-gl/gl-infrastructure/src/main/resources/db/migration/V2__create_gl_account_tables.sql
-- TODO: Add SQL statements.
