-- Placeholder generated from COMPLETE_STRUCTURE.txt
-- Path: bounded-contexts/finance/finance-gl/gl-infrastructure/src/main/resources/db/migration/V4__create_fiscal_period_tables.sql
-- TODO: Add SQL statements.
