-- Placeholder generated from COMPLETE_STRUCTURE.txt
-- Path: bounded-contexts/finance/finance-gl/gl-infrastructure/src/main/resources/db/migration/V6__create_exchange_rate_tables.sql
-- TODO: Add SQL statements.
